Improve error message for invalid regex to search
Fixes https://github.com/Homebrew/homebrew/issues/50131

Previously if a bad regexp was passed to `brew search` it would produce
an output of:

```
$ brew search '/++[/'
Error: target of repeat operator is not specified: /++[/
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/search.rb:93:in `initialize'
/usr/local/Library/Homebrew/cmd/search.rb:93:in `new'
/usr/local/Library/Homebrew/cmd/search.rb:93:in `query_regexp'
/usr/local/Library/Homebrew/cmd/search.rb:43:in `search'
/usr/local/Library/brew.rb:83:in `<main>'
$
```

This commit makes it so that if `Regexp.new` is passed an invalid
regular expression that the error message now looks something like:

```
$ brew search '/++[/'
/++[/ is not a valid regex
$
```